(function exposeThemes(root) {
  const themes = {
    default: {
      id: 'default',
      label: 'Default doll',
      trayDrinkLabel: 'Drink now',
      assetFolder: 'assets/themes/default',
      buttons: {
        yes: 'YES, I DRANK',
        snooze: 'SNOOZE',
      },
      cssVars: {
        '--bubble-bg': '#fdfdf7',
        '--bubble-border': '#1c1c1c',
        '--bubble-text': '#1c1c1c',
        '--bubble-shadow': 'rgba(0, 0, 0, 0.18)',
        '--button-yes-bg': '#37c24a',
        '--button-yes-hover': '#2fae41',
        '--button-yes-text': '#ffffff',
        '--button-snooze-bg': '#fdfdf7',
        '--button-snooze-hover': '#ececec',
        '--button-snooze-text': '#1c1c1c',
        '--pet-shadow': 'rgba(0, 0, 0, 0.28)',
      },
      prompts: [
        'Time to drink water to keep your skin glowing!',
        'Hydration check! Take a sip of water',
        'Water break! Your body will thank you.',
        'Psst... a few sips of water? Stay glowing!',
        "Don't forget me - drink some water!",
      ],
      namedPrompts: [
        '{name}, time to drink water to keep your skin glowing!',
        '{name}, hydration check! Take a sip',
        'Water break, {name}! Your body will thank you.',
        'Psst {name}... a few sips of water? Stay glowing!',
        "Don't forget me, {name} - drink some water!",
      ],
      cheers: [
        'Yay! Stay glowing',
        'Amazing! Keep it up',
        "That's the spirit!",
        'Hydrated and happy!',
      ],
      namedCheers: [
        'Yay {name}! Stay glowing',
        'Amazing, {name}! Keep it up',
        "That's the spirit, {name}!",
        'Hydrated and happy, {name}!',
      ],
      snooze: "I'll come back in {minutes} mins!",
      namedSnooze: "I'll come back in {minutes} mins, {name}!",
      goodbye: 'See you in a bit!',
      confettiGlyphs: ['drop', 'sparkle', 'heart', 'bubble', 'star'],
      confettiColors: ['#37c24a', '#4aa3df', '#ffd447', '#ff7a59', '#8ad6ff'],
    },
    'baby-yoda': {
      id: 'baby-yoda',
      label: 'Baby Yoda',
      trayDrinkLabel: 'Tiny hydration mission',
      assetFolder: 'assets/themes/baby-yoda',
      buttons: {
        yes: 'SIP TAKEN',
        snooze: 'SNOOZE',
      },
      cssVars: {
        '--bubble-bg': '#f8f1df',
        '--bubble-border': '#3e6f4b',
        '--bubble-text': '#193724',
        '--bubble-shadow': 'rgba(62, 111, 75, 0.24)',
        '--button-yes-bg': '#73b66b',
        '--button-yes-hover': '#5fa157',
        '--button-yes-text': '#0f2618',
        '--button-snooze-bg': '#d9c6a5',
        '--button-snooze-hover': '#cbb48d',
        '--button-snooze-text': '#2f2418',
        '--pet-shadow': 'rgba(115, 182, 107, 0.34)',
      },
      prompts: [
        'A sip, you must take.',
        'Small sip, big energy.',
        'The bottle calls. Listen, you should.',
        'In the hydration force, trust you can.',
        'Thirst on the path, welcome it is not. Water now.',
      ],
      namedPrompts: [
        '{name}, a sip you must take.',
        'Small sip, big energy, {name}.',
        '{name}, the bottle calls. Listen, you should.',
        'In the hydration force, trust you can, {name}.',
        'Thirst on the path, welcome it is not, {name}. Water now.',
      ],
      cheers: [
        'Strong with the sip, you are.',
        'Very good. Hydrated, you become.',
        'Small victory, big glow.',
        'The bottle smiled inside.',
      ],
      namedCheers: [
        'Strong with the sip, you are, {name}.',
        'Very good, {name}. Hydrated, you become.',
        'Small victory, big glow, {name}.',
        '{name}, the bottle smiled inside.',
      ],
      snooze: 'Return in {minutes} mins, I will.',
      namedSnooze: 'Return in {minutes} mins, {name}, I will.',
      goodbye: 'See you soon, tiny sip.',
      confettiGlyphs: ['drop', 'sparkle', 'star', 'heart', 'dot'],
      confettiColors: ['#73b66b', '#d9c6a5', '#f8f1df', '#3e6f4b', '#f0c96a'],
    },
    'darth-vader': {
      id: 'darth-vader',
      label: 'Darth Vader',
      trayDrinkLabel: 'Imperial hydration order',
      assetFolder: 'assets/themes/darth-vader',
      buttons: {
        yes: 'ORDER OBEYED',
        snooze: 'DELAY MISSION',
      },
      cssVars: {
        '--bubble-bg': '#101114',
        '--bubble-border': '#d72638',
        '--bubble-text': '#f4f4f5',
        '--bubble-shadow': 'rgba(215, 38, 56, 0.34)',
        '--button-yes-bg': '#d72638',
        '--button-yes-hover': '#b91f2f',
        '--button-yes-text': '#ffffff',
        '--button-snooze-bg': '#2f343d',
        '--button-snooze-hover': '#3d444f',
        '--button-snooze-text': '#f4f4f5',
        '--pet-shadow': 'rgba(215, 38, 56, 0.42)',
        '--bubble-font-size': '10px',
        '--bubble-line-height': '2',
        '--bubble-letter-spacing': '1px',
        '--button-font-size': '8px',
        '--button-letter-spacing': '0.8px',
      },
      prompts: [
        'I am not your father, but I told you to drink water.',
        'Your lack of water is disturbing.',
        'Join the hydrated side of the force.',
        'Thirst underestimates the power of the bottle.',
        'Breathe deeply. Now drink water.',
      ],
      namedPrompts: [
        '{name}, I am not your father, but I told you to drink water.',
        '{name}, your lack of water is disturbing.',
        'Join the hydrated side of the force, {name}.',
        '{name}, thirst underestimates the power of the bottle.',
        'Breathe deeply, {name}. Now drink water.',
      ],
      cheers: [
        'The hydration is strong with you.',
        'Impressive. Another sip mastered.',
        'The cup has been defeated.',
        'Your bottle has fulfilled its destiny.',
      ],
      namedCheers: [
        'The hydration is strong with you, {name}.',
        'Impressive, {name}. Another sip mastered.',
        'The cup has been defeated, {name}.',
        '{name}, your bottle has fulfilled its destiny.',
      ],
      snooze: 'I will delay your mission for {minutes} mins.',
      namedSnooze: 'I will delay your mission for {minutes} mins, {name}.',
      goodbye: 'You may continue. I am watching.',
      confettiGlyphs: ['drop', 'sparkle', 'diamond', 'star', 'dot'],
      confettiColors: ['#d72638', '#f4f4f5', '#2f343d', '#7f1d1d', '#a1a1aa'],
    },
  };

  if (typeof module === 'object' && module.exports) {
    module.exports = themes;
  } else {
    root.HYDRATE_THEMES = themes;
  }
})(typeof globalThis === 'object' ? globalThis : window);
